Fix post refactoring merge Oracle replication issues
This commit addresses the following Oracle replication issues that
arises after merging in the upstream code refactoring changes:

Issue: Cannot get replication instance for 'oracle': __init__() takes
exactly 2 arguments (1 given)
Cause: Refactored base class removed the unused variable on the
constructor signature.

Issue: ORA-12514: TNS:listener does not currently know of service
requested in connect descriptor.
Cause: After refactoring, constructor of the replication class is
called before the oracle.cnf file is being created. db_name value is
None as a result causing the crash.

Issue:
File trove/guestagent/datastore/oracle/manager.py, in attach_replica
replication.prepare_slave(replica_info)
NameError: global name 'replication' is not defined
Cause: Preceding "self" is missing at the function call.

Change-Id: Ib22c5966f6a6fa8324c3a67b42e2221c4b2fcd7b
Closed-Bug: dbaas-1523