Fix trove create error for Oracle
Oracle database creation fails with the following guestagent error:
DatabaseError: ORA-01920: user name <user> conflicts with another
user or role name

The latest refactored prepare method in trove.guestagent.datastore.manager
creates the user specified in the CLI parameter. However, the
do_prepare method implementation for Oracle did not take into
account this abstraction, and attempted to create the same user
after it has been created, causing the error.

This commit removes the duplicate user creation code from the
do_prepare method implementation for Oracle.

Change-Id: Ia73e4f3971fdea634ddb95f1e3a6fdfa62550d80
Closes-Bug: dbaas-1520